// Simplified localization - can be enhanced later
export const local: Record<string, string> = {
    download: "DOWNLOAD GAME",
    navItemHome: "Home",
    navItemNews: "News",
    navItemDonation: "Donation",
    navItemLanguage: "Language",
    navItemAccount: "Account",
    navSubItemLogin: "Login",
    navSubItemRegister: "Register",
    navSubItemProfile: "Profile",
    navSubItemLogout: "Logout",
    login: "Login",
    username: "Username",
    password: "Password",
    email: "Email",
    register: "Register",
    confirmPassword: "Confirm Password",
    usernameError: "* Username should be 2~16 characters long.",
    passwordError: "* Password should be 2~16 characters long.",
    emailError: "* Check the Email field.",
    confirmPasswordError: "* Passwords must match.",
    beginAdventure: "BEGIN YOUR ADVENTURE.",
    registerDownload: "Register & download today and enjoy the world of DBO Daebak",
    homeRegister: "REGISTER",
    homeDownload: "DOWNLOAD",
    serverStatus: "SERVER STATUS",
    updateEveryMinute: "(Updates every minute)",
    playerCount: "Player Count",
    auth: "Auth",
    ch0: "Channel 0",
    ch9: "Channel 9",
    online: "Online",
    offline: "Offline",
    userInfo: "User Info",
    characters: "Characters",
    donations: "Donations",
    cashPoints: "Cash Points",
    changePassword: "CHANGE PASSWORD",
    donate: "DONATE",
    currentPassword: "Current Password",
    newPassword: "New Password",
    sp: "SP",
    wagu: "Wagu",
    payment: "Payment",
    paymentDescription: "Complete your purchase to receive your Cash Points instantly",
    paymentDetails: "Payment Details",
    enterCardInfo: "Enter your card information to complete the purchase",
    payNow: "Pay now",
    paymentSucceeded: "Payment succeeded!",
    paymentProcessing: "Your payment is processing.",
    paymentFailed: "Your payment was not successful, please try again.",
    paymentError: "Something went wrong.",
    unexpectedError: "An unexpected error occurred.",
    retry: "Retry",
    dailyLoginRewards: "Daily Login Rewards",
    nextReset: "Next Reset:",
    selectCharacterTitle: "Select Character to Receive Rewards",
    day: "Day",
    bonus: "Bonus",
    claimed: "Claimed",
    claim: "Claim",
    notAvailable: "Not Available",
    bonusRewardDesc: "Bonus reward can be claimed after completing day 28.",
    dailyRaffle: "Daily Raffle",
    enterForChance: "Enter for a chance to win Cash Points!",
    currentPot: "Current Pot",
    timeLeft: "Time Left",
    enterRaffle: "Enter Raffle",
    enterRaffleCost: "Enter Raffle (5 CP)",
    currentEntries: "Current Entries",
    recentWinners: "Recent Winners",
    noEntriesYet: "No entries yet",
    noWinnersYet: "No winners yet",
    confirmRaffleEntry: "Confirm Raffle Entry",
    confirmRaffleDesc: "Are you sure you want to enter the raffle?",
    totalCost: "Total cost:",
    cancel: "Cancel",
    confirm: "Confirm",
    entering: "Entering...",
    loading: "Loading...",
    donation: "DONATION",
    donationEvent: "Donation event is active! +{0}% cash points",
    firstTimeBonus: "First Time Bonus!",
    firstTimeBonusDesc: "Get 2x Cash Points on your first donation!",
    purchaseNow: "Purchase Now",
    price: "Price",
    eventBonus: "Event Bonus",
    totalCP: "Total CP",
    totalDonated: "Total Donated",
    donationTiers: "Donation Tiers",
    starter: "Starter",
    basicSupporterTitle: "Basic Supporter Title",
    accessGlobalChat: "Access to Global Chat",
    bronzeSupporter: "Bronze Supporter",
    exclusiveBronzeTitle: "Exclusive Bronze Title",
    bronzeSupporterBadge: "Bronze Supporter Badge",
    accessBronzeChat: "Access to Bronze-only chat channel",
    silverSupporter: "Silver Supporter",
    exclusiveSilverTitle: "Exclusive Silver Title",
    silverSupporterBadge: "Silver Supporter Badge",
    accessSilverChat: "Access to Silver-only chat channel",
    monthlySilverBox: "Monthly Silver Box",
    goldSupporter: "Gold Supporter",
    exclusiveGoldTitle: "Exclusive Gold Title",
    goldSupporterBadge: "Gold Supporter Badge",
    accessGoldChat: "Access to Gold-only chat channel",
    monthlyGoldBox: "Monthly Gold Box",
    customChatColor: "Custom Chat Color",
    platinumSupporter: "Platinum Supporter",
    exclusivePlatinumTitle: "Exclusive Platinum Title",
    platinumSupporterBadge: "Platinum Supporter Badge",
    accessPlatinumChat: "Access to Platinum-only chat channel",
    monthlyPlatinumBox: "Monthly Platinum Box",
    specialMount: "Special Mount",
    diamondSupporter: "Diamond Supporter",
    exclusiveDiamondTitle: "Exclusive Diamond Title",
    diamondSupporterBadge: "Diamond Supporter Badge",
    accessDiamondChat: "Access to Diamond-only chat channel",
    monthlyDiamondBox: "Monthly Diamond Box",
    customPet: "Custom Pet",
};

// Helper function for string formatting
export const formatString = (template: string, ...args: any[]): string => {
    return template.replace(/{(\d+)}/g, (match, index) => {
        return args[parseInt(index)] !== undefined ? args[parseInt(index)] : match;
    });
};
