// Simplified localization - can be enhanced later
export const local: Record<string, string> = {
    download: "DOWNLOAD GAME",
    navItemHome: "Home",
    navItemNews: "News",
    navItemDonation: "Donation",
    navItemLanguage: "Language",
    navItemAccount: "Account",
    navSubItemLogin: "Login",
    navSubItemRegister: "Register",
    navSubItemProfile: "Profile",
    navSubItemLogout: "Logout",
    login: "Login",
    username: "Username",
    password: "Password",
    email: "Email",
    register: "Register",
    confirmPassword: "Confirm Password",
    usernameError: "* Username should be 2~16 characters long.",
    passwordError: "* Password should be 2~16 characters long.",
    emailError: "* Check the Email field.",
    confirmPasswordError: "* Passwords must match.",
    beginAdventure: "BEGIN YOUR ADVENTURE.",
    registerDownload: "Register & download today and enjoy the world of DBO Daebak",
    homeRegister: "REGISTER",
    homeDownload: "DOWNLOAD",
    serverStatus: "SERVER STATUS",
    updateEveryMinute: "(Updates every minute)",
    playerCount: "Player Count",
    auth: "Auth",
    ch0: "Channel 0",
    ch9: "Channel 9",
    online: "Online",
    offline: "Offline",
    userInfo: "User Info",
    characters: "Characters",
    donations: "Donations",
    cashPoints: "Cash Points",
    changePassword: "CHANGE PASSWORD",
    donate: "DONATE",
    currentPassword: "Current Password",
    newPassword: "New Password",
    sp: "SP",
    wagu: "Wagu",
    payment: "Payment",
    paymentDescription: "Complete your purchase to receive your Cash Points instantly",
    paymentDetails: "Payment Details",
    enterCardInfo: "Enter your card information to complete the purchase",
    payNow: "Pay now",
    paymentSucceeded: "Payment succeeded!",
    paymentProcessing: "Your payment is processing.",
    paymentFailed: "Your payment was not successful, please try again.",
    paymentError: "Something went wrong.",
    unexpectedError: "An unexpected error occurred.",
    retry: "Retry",
    dailyLoginRewards: "Daily Login Rewards",
    nextReset: "Next Reset:",
    selectCharacterTitle: "Select Character to Receive Rewards",
    day: "Day",
    bonus: "Bonus",
    claimed: "Claimed",
    claim: "Claim",
    notAvailable: "Not Available",
    bonusRewardDesc: "Bonus reward can be claimed after completing day 28.",
    dailyRaffle: "Daily Raffle",
    enterForChance: "Enter for a chance to win Cash Points!",
    currentPot: "Current Pot",
    timeLeft: "Time Left",
    enterRaffle: "Enter Raffle",
    enterRaffleCost: "Enter Raffle (5 CP)",
    currentEntries: "Current Entries",
    recentWinners: "Recent Winners",
    noEntriesYet: "No entries yet",
    noWinnersYet: "No winners yet",
    confirmRaffleEntry: "Confirm Raffle Entry",
    confirmRaffleDesc: "Are you sure you want to enter the raffle?",
    totalCost: "Total cost:",
    cancel: "Cancel",
    confirm: "Confirm",
    entering: "Entering...",
    loading: "Loading...",
    donation: "DONATION",
    donationEvent: "Donation event is active! +{0}% cash points",
    firstTimeBonus: "First Time Bonus!",
    firstTimeBonusDesc: "Get 2x Cash Points on your first donation!",
    purchaseNow: "Purchase Now",
    price: "Price",
    eventBonus: "Event Bonus",
    totalCP: "Total CP",
    totalDonated: "Total Donated",
    donationTiers: "Donation Tiers",
    starter: "Starter",
    basicSupporterTitle: "Basic Supporter Title",
    accessGlobalChat: "Access to Global Chat",
    bronzeSupporter: "Bronze Supporter",
    exclusiveBronzeTitle: "Exclusive Bronze Title",
    bronzeSupporterBadge: "Bronze Supporter Badge",
    accessBronzeChat: "Access to Bronze-only chat channel",
    silverSupporter: "Silver Supporter",
    exclusiveSilverTitle: "Exclusive Silver Title",
    silverSupporterBadge: "Silver Supporter Badge",
    accessSilverChat: "Access to Silver-only chat channel",
    monthlySilverBox: "Monthly Silver Box",
    goldSupporter: "Gold Supporter",
    exclusiveGoldTitle: "Exclusive Gold Title",
    goldSupporterBadge: "Gold Supporter Badge",
    accessGoldChat: "Access to Gold-only chat channel",
    monthlyGoldBox: "Monthly Gold Box",
    customChatColor: "Custom Chat Color",
    platinumSupporter: "Platinum Supporter",
    exclusivePlatinumTitle: "Exclusive Platinum Title",
    platinumSupporterBadge: "Platinum Supporter Badge",
    accessPlatinumChat: "Access to Platinum-only chat channel",
    monthlyPlatinumBox: "Monthly Platinum Box",
    specialMount: "Special Mount",
    diamondSupporter: "Diamond Supporter",
    exclusiveDiamondTitle: "Exclusive Diamond Title",
    diamondSupporterBadge: "Diamond Supporter Badge",
    accessDiamondChat: "Access to Diamond-only chat channel",
    monthlyDiamondBox: "Monthly Diamond Box",
    customPet: "Custom Pet",
    coreFeatures: "Core Features",
    dualClass: "Dual Class",
    dualClassDesc: "Choose 2 classes per character and switch freely between both via a special in-game item. Use both sub-class skills freely without having to switch classes after learning the skills.",
    equipmentUpgrade: "Equipment Upgrade System",
    equipmentUpgradeDesc: "Gear base stats are rarity-based. As you upgrade, your gear gains random base stats or upgrades existing base stats every 3 upgrades. Each base stat and upgrade stat has a min-max value which will add to the difficulty of obtaining endgame-worthy stats.",
    fastGameplay: "Fast Gameplay",
    fastGameplayDesc: "High EXP, move speed, fly speed, and stats for an accelerated experience.",
    channelBuffs: "Channel & Global Buffs",
    channelBuffsDesc: "Channel bonus stats and global buffs to enhance your gameplay.",
    craftedEquipment: "Crafted Equipment",
    craftedEquipmentDesc: "Bonus upgrade stats upgradable via website. Currency obtained from CCBD.",
    upgradeEquipmentStats: "Upgrade Equipment Stats",
    ccbdToken: "CCBD Token",
    ccbdLimit: "CCBD Limit",
    ccbdEntry: "CCBD Entry",
    currentUpgradedStats: "Current upgraded equipment stats",
    increaseStatsBy: "Add +{0}% (total: {1}%)",
    craftedEquipmentOnly: "This upgrade applies only to crafted equipment.",
    characterDetails: "Character Details",
    refill: "Refill",
    refillConfirmTitle: "Refill CCBD Entry",
    refillConfirmMessage: "Refill CCBD Entry to max ({0}) for 25 Cash Points?",
    refillSuccess: "CCBD Entry refilled successfully",
    refillInsufficientCP: "Not enough Cash Points. Need 25 CP.",
    applyEquipmentUpgrade: "Apply upgrade",
    upgradeEquipmentSuccess: "Equipment stats upgraded successfully",
    statsPreviewTitle: "Stats Preview",
    statsPreviewHint:
        "List matches the server: slot, level, and item rank. Tap a row for a short roll preview for that stat.",
    enchantPreviewLoadError: "Could not load enchant table (table_item_enchant_data_rows.csv).",
    enchantPreviewRank: "Item rank",
    enchantPreviewLevel: "Required level",
    enchantPreviewCategory: "Equipment",
    enchantPreviewBefore: "At current Item Worth ({0}%)",
    enchantPreviewAfter: "After upgrade ({0}% Item Worth)",
    enchantPreviewRange: "min {0} — max {1}",
    enchantPreviewWorthPool: "Worth pool (float): {0}",
    enchantPreviewFourthSlotNote:
        "The fourth random option always uses the maximum affordable value for the rolled line (not a 1…max roll). Max shown here is the first-slot upper bound; late slots may be lower.",
    enchantPreviewDisclaimer:
        "Preview uses worth pool and table costs only. Some in-game kits and bonuses are not shown.",
    statModalReroll: "Reroll simulation",
    statModalRerollAria: "Reroll random sample values for this stat",
    statModalRerollHint: "Same stat you picked; new random rolls.",
    statModalNotOnRank: "This stat is not in the random pool for {0} items.",
    statModalCannotRoll: "With these settings this line cannot roll a positive value (check required level and worth).",
    statModalLinesOnCreate: "{0} different random stats roll when a {1} item is created.",
    statModalSampleItemTitle: "On creation",
    statModalSampleItemCaption:
        "A new {1} item rolls {0} random stat lines (server: rank − 1). Line 1 is your selected stat when it can roll; other lines are sampled like the server. Ranges are 1 through each line’s max for the worth pool. Gear upgrade steps use this same line order (so your selected stat can be bumped).",
    statModalLineGenRange: "Line {0}: {1} {2}~{3}",
    statModalLineN: "Line {0}:",
    statModalLastLineMax: "max",
    statModalUpgradeGearTitle: "Gear upgrade steps (+3 … +15)",
    statModalUpgradeGearIntro:
        "Matches GameServer `item.cpp`: each +3/+6/+9/+12/+15 step picks a random-option slot index like the client (empty slot when that milestone allows it, otherwise a random index among the first slots), then either rolls a **new** stat on an empty slot or **bumps** an existing line by a random 1…max. Creation lines above are in display order (selected stat first when possible); upgrade uses the server’s slot order from the sampled roll. Reroll redraws the whole sample.",
    statModalUpgradeGearIntro2: "",
    statModalGearUpgradeLevel: "Equipment +{0}",
    statModalUpgradeRollRange: "Random from 1 to {0}",
    statModalUpgradeNewStatInline: "New stat",
    statModalUpgradeFooter: "Different stats use different costs, so maximums and bump sizes differ.",
    statModalAfterUpgradeTitle: "After +15 — result",
    statModalAfterUpgradeCaption:
        "Filled random-option slots in server order: the same lines as “On creation” (plus any extra slot filled during upgrades on Rare and below; Legendary already has rank − 1 lines at create). Line numbers are in-game slot indices.",
    statModalIncompleteGen: "Could not fill every line (pool, exclusivity, or frequencies). Try another level or slot.",
    statModalTechnicalDetails: "Details",
    statModalDetailLevel: "Required level",
    statModalDetailItemWorth: "Item Worth",
    statModalDetailWorthPool: "Worth pool",
    statModalDetailCost: "Cost per point",
    enchantAllOptionsTitle: "All random options (min–max)",
    enchantAllOptionsOpen: "View all stats (min–max)",
    enchantExampleLabel: "Example: equipment +{0} (illustrative)",
    enchantNoRows: "No eligible random options for this selection.",
    enchantNoRowsForEquipment: "No enchant rows match this equipment slot and required level (check dwEquip and level range in the CSV).",
    enchantTierModalTitle: "Example: equipment upgrade milestones",
    enchantTierModalSubtitle: "Possible min/max roll per stat at +3 / +6 / +9 / +12 / +15 upgrade (first-slot bound)",
    enchantStatColumn: "Stat",
    enchantTierExamplesAria: "Open example min/max for equipment upgrade +3 through +15",
    statDetailEnchantTblidx: "Enchant tblidx",
    statDetailEffectSe: "System effect (seTblidx)",
    statDetailCostPerPoint: "Worth cost per option point: {0}",
    statDetailTierTitle: "Min/max at each equipment upgrade milestone (first-slot bound)",
    statDetailSameLineFourRolls: "Same stat, four rolls in a row",
    statDetailSameLineFourRollsHint:
        "Illustrative only: assumes this exact line is rolled four times, max value each time, before other options exist.",
    statDetailItemWorth: "Item Worth",
    statDetailRollN: "Roll {0}",
    statDetailTotalPoints: "Sum of option values: {0}",
    statDetailRemainingWorth: "Remaining worth pool after: {0}",
    statDetailGreedyBuild: "Four different stats — greedy “max” build",
    statDetailGreedyBuildHint:
        "Illustrative: picks four different enchant lines (lowest cost first), each at first-slot max. Order differs in-game.",
    statDetailIncludedInGreedy: "This stat is in this greedy set",
    statDetailNotInGreedy: "Cheaper lines consumed the pool first",
    statDetailOpenAria: "Open upgrade simulation for this stat",
    statDetailMaxValueCap: "cap {0}",
    statDetailWorthHint:
        "W matches server Dbo_GetItemWorth using your character Item Worth (crafted %). Columns are equipment +3 … +15 (when a roll fires), not extra % tiers. Max roll = min(floor(W / cost), wMaxValue when set in table).",
    statDetailCharItemWorthUsed: "Character Item Worth (crafted bonus): {0}%",
    statDetailEquipmentPlus: "Equipment +{0}",
    statDetailSpreadTitle: "Sample roll per upgrade milestone",
    statDetailSpreadHint:
        "Each row: one random eligible stat and one roll in [1 … max] (like RandomRange). Same worth pool each time. Seed = character + stat.",
    statDetailRollMax: "max",
    statDetailMaxPerTierTitle: "This stat — first-slot max (one roll)",
    statDetailMaxPerTierHint:
        "Each milestone uses the same worth pool; the +3 … +15 labels are when rolls occur, not different pools.",
    statDetailFirstSlotMaxOneRoll: "First-slot max for this stat on one roll: +{0}",
    statDetailRollMilestonesNote:
        "In-game: a gen/upgrade step runs every 3 equipment upgrade levels (+3 … +15).",
    statDetailFourSlotsTitle: "One item — four random lines (your worth pool)",
    statDetailFourSlotsHint:
        "Uses a single worth pool ≈{0} and four distinct enchant lines (greedy, lowest cost first), like four ProcessRandomOption steps.",
};

// Helper function for string formatting
export const formatString = (template: string, ...args: any[]): string => {
    return template.replace(/{(\d+)}/g, (match, index) => {
        return args[parseInt(index)] !== undefined ? args[parseInt(index)] : match;
    });
};
